# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f91ae818d058098cbcce71efc722e4ae44cee3143b1172a02769199846134653d8b4e9c58df7ca5f2858d518a61bdf922dc5346f92cf5a04a5464182f817ba8

test:
  secret_key_base: 40d2f87a483e9e03eca1e687075e85bcbfa057b70d9316e1422bbc851b51d97a8de1c882a783d78fff1c59d1cbbfe80f3b38a0091d5028a0465ca785c07043ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
